version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://app:8080/v1/datasetLeistungsnachweis # Wenn die API im selben Docker-Compose-Netzwerk läuft
