version: '3'
services:
  assessment:
    image: mrksdh/assessment
    ports:
      - "8080:8080"

  calculator:
    build: ./calculator
    depends_on:
      - assessment
    environment:
      ASSESSMENT_URL: http://assessment:8080/v1/dataset
      RESULT_URL: http://assessment:8080/v1/result
