name: Test Java CloudUsageApp with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker Image
      run: docker build . -t cloud-usage-app

    - name: Run Docker Container
      run: |
        docker run -d -p 8080:8080 cloud-usage-app
    
    - name: Verify Docker Container is Running
      run: docker ps | grep cloud-usage-app

    - name: Clean up Docker (optional)
      run: docker system prune -f
