name: Test Application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # DockerHub Username als Secret hinzufügen
        password: ${{ secrets.DOCKER_PASSWORD }} # DockerHub Password als Secret hinzufügen

    - name: Build Docker Images
      run: docker-compose build

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Wait for services to start
      run: |
        echo "Waiting for services to be ready..."
        sleep 20  # Wartezeit für den Start der Services

    - name: Check if service is running
      run: |
        echo "Checking if the service is running..."
        curl --fail localhost:8080/v1/dataset || exit 1

    - name: Verify Results
      run: |
        echo "Verifying results..."
        curl --fail localhost:8080/v1/result || exit 1

    - name: Tear down Docker Compose
      run: docker-compose down

