name: Test Application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Images
      run: |
        docker-compose build || {
          echo "Build failed, cleaning up..."
          docker-compose down --volumes --rmi all
          docker system prune -a -f
          exit 1
        }

    - name: Run Docker Compose
      run: |
        docker-compose up -d || {
          echo "Docker Compose failed, cleaning up..."
          docker-compose down --volumes --rmi all
          docker system prune -a -f
          exit 1
        }

    - name: Wait for services to start
      run: sleep 20  # Warte, bis die Services gestartet sind

    - name: Verify Results
      run: curl http://localhost:8080/v1/result

    - name: Cleanup Docker environment after tests
      if: always()
      run: |
        docker-compose down --volumes --rmi all
        docker system prune -a -f
